const { DataTypes } = require('sequelize');
const { sequelize } = require('../../config/pgdb');

const BillMaster = sequelize.define('BillMaster', {
  billId: { type: DataTypes.STRING, unique: true },
  FK_BillingCompanyId: { type: DataTypes.INTEGER },
  FK_FinYearId: { type: DataTypes.INTEGER },
  FK_BranchId: { type: DataTypes.INTEGER },
  FK_BillTypeId: { type: DataTypes.INTEGER },
  FK_CategoryId: { type: DataTypes.INTEGER },
  FK_BillSerieseId: { type: DataTypes.INTEGER },
  BillNo: { type: DataTypes.STRING },
  BillDate: { type: DataTypes.DATE },
  BillTime: { type: DataTypes.STRING },
  FK_RegId: { type: DataTypes.STRING },
  FK_IPDId: { type: DataTypes.STRING },
  FK_DoctorId: { type: DataTypes.INTEGER },
  FK_DrDeptID: { type: DataTypes.INTEGER },
  FK_ReferredById: { type: DataTypes.INTEGER },
  FK_PartyId: { type: DataTypes.STRING },
  IsMLC: { type: DataTypes.BOOLEAN, defaultValue: false },
  IsAcademic: { type: DataTypes.BOOLEAN, defaultValue: false },
  AgeYear: { type: DataTypes.INTEGER },
  AgeMonth: { type: DataTypes.INTEGER },
  AgeDays: { type: DataTypes.INTEGER },
  TotalAmt: { type: DataTypes.FLOAT, defaultValue: 0 },
  ServiceChargeAmt: { type: DataTypes.FLOAT, defaultValue: 0 },
  DiscountAmt: { type: DataTypes.FLOAT, defaultValue: 0 },
  NetBillAmt: { type: DataTypes.FLOAT, defaultValue: 0 },
  RateType: { type: DataTypes.STRING },
  Remarks: { type: DataTypes.TEXT },
  Iscancel: { type: DataTypes.BOOLEAN, defaultValue: false },
  FK_CreatedById: { type: DataTypes.INTEGER },
  FK_CancelledById: { type: DataTypes.INTEGER },
  CancelledDateTime: { type: DataTypes.DATE },
  PrintCount: { type: DataTypes.INTEGER, defaultValue: 0 },
  FreeReason: { type: DataTypes.STRING },
  IsActive: { type: DataTypes.BOOLEAN, defaultValue: true },
  PK_SynchId: { type: DataTypes.INTEGER },
  OLDBillID: { type: DataTypes.INTEGER },
  OLDBillNo: { type: DataTypes.STRING },
  OLDRegID: { type: DataTypes.INTEGER },
  ReportDeliveryDateTime: { type: DataTypes.DATE },
  FK_OrganizerId: { type: DataTypes.INTEGER },
  Tokenno: { type: DataTypes.STRING },
  Cancelreason: { type: DataTypes.STRING },
  HospitalDiscount: { type: DataTypes.FLOAT, defaultValue: 0 },
  MOUDiscount: { type: DataTypes.FLOAT, defaultValue: 0 },
  FK_PaytypeID: { type: DataTypes.INTEGER },
  BillRefID: { type: DataTypes.INTEGER },
  Diagnosis: { type: DataTypes.TEXT },
}, { tableName: 'billmasters', timestamps: true });

module.exports = BillMaster;
