// models/billmaster.js
const mongoose = require('mongoose');

const BillMasterSchema = new mongoose.Schema({
  billId: { type: String, unique: true, sparse: true },
  PK_BillId: { type: Number },
  FK_BillingCompanyId: { type: Number },
  FK_FinYearId: { type: Number },
  FK_BranchId: { type: Number },
  FK_BillTypeId: { type: Number },
  FK_CategoryId: { type: Number },
  FK_BillSerieseId: { type: Number },
  BillNo: { type: String },
  BillDate: { type: Date },
  BillTime: { type: String },
  FK_RegId: { type: Number },
  FK_IPDId: { type: Number },
  FK_DoctorId: { type: Number },
  FK_DrDeptID: { type: Number },
  FK_ReferredById: { type: Number },
  FK_PartyId: { type: Number },
  IsMLC: { type: Boolean, default: false },
  IsAcademic: { type: Boolean, default: false },
  AgeYear: { type: Number },
  AgeMonth: { type: Number },
  AgeDays: { type: Number },
  TotalAmt: { type: Number, default: 0 },
  ServiceChargeAmt: { type: Number, default: 0 },
  DiscountAmt: { type: Number, default: 0 },
  NetBillAmt: { type: Number, default: 0 },
  RateType: { type: String },
  Remarks: { type: String },
  Iscancel: { type: Boolean, default: false },
  FK_CreatedById: { type: Number },
  FK_CancelledById: { type: Number },
  CancelledDateTime: { type: Date },
  PrintCount: { type: Number, default: 0 },
  FreeReason: { type: String },
  IsActive: { type: Boolean, default: true },
  PK_SynchId: { type: Number },
  OLDBillID: { type: Number },
  OLDBillNo: { type: String },
  OLDRegID: { type: Number },
  ReportDeliveryDateTime: { type: Date },
  FK_OrganizerId: { type: Number },
  Tokenno: { type: String },
  Cancelreason: { type: String },
  HospitalDiscount: { type: Number, default: 0 },
  MOUDiscount: { type: Number, default: 0 },
  FK_PaytypeID: { type: Number },
  BillRefID: { type: Number },
  Diagnosis: { type: String },
}, { timestamps: true });

module.exports = mongoose.model('BillMaster', BillMasterSchema);
