// models/opdappointment.js
const mongoose = require('mongoose');

const OpdAppointmentSchema = new mongoose.Schema({
  appointmentId: { type: String, required: true, unique: true, index: true }, // PK_AppointmentId
  fkBranchId: { type: String },
  fkForBranchId: { type: String },
  bookingDate: { type: Date },
  daySrNo: { type: Number },
  fkApptTypeId: { type: String },
  fkRegId: { type: String },
  apptDate: { type: Date },
  apptTime: { type: String },
  initial: { type: String },
  firstName: { type: String },
  lastName: { type: String },
  ageYear: { type: Number },
  ageMonth: { type: Number },
  ageDays: { type: Number },
  dob: { type: Date },
  sex: { type: String, enum: ['M','F','O', null] },
  address: { type: String },
  emailAddress: { type: String },
  fkCityId: { type: String },
  contactNo: { type: String },
  fkRefById: { type: String },
  fkConsultantId: { type: String },
  isVIP: { type: Boolean, default: false },
  fkTakenOnId: { type: String },
  remarks: { type: String },
  isConfirm: { type: Boolean, default: false },
  isCancelled: { type: Boolean, default: false },
  fkCreatedById: { type: String },
  isReScheduled: { type: Boolean, default: false },
  rescheduleDate: { type: Date },
  isSentSMS: { type: Boolean, default: false },
  isSentSMSReScheduled: { type: Boolean, default: false },
  isActive: { type: Boolean, default: true },
  pkSynchId: { type: String },
  isSentSMSReminder: { type: Boolean, default: false },
  fkServiceId: { type: String },
  isSAP: { type: Boolean, default: false },
  fkModifiedById: { type: String },
  fkOccupationId: { type: String },
  token_no: { type: String },
  fkConsultationServiceID: { type: String },
  consultationAmount: { type: Number },
  discount: { type: Number },
  netConsultation: { type: Number },
  transcationID: { type: String },
  paymentStatus: { type: String },
  payType: { type: String },
  checkSumHash: { type: String },
  isVisitCreated: { type: Boolean, default: false },
  isTokenGenerated: { type: Boolean, default: false },
  complaints: { type: String },
  entrySource: { type: String },
  fkMobileAppUserId: { type: String },
  nationalID: { type: String }
}, { timestamps: true });

module.exports = mongoose.model('OpdAppointment', OpdAppointmentSchema);
