// models/opdvisitmaster.js
const mongoose = require('mongoose');

const OpdVisitMasterSchema = new mongoose.Schema({
  pkVisitId: { type: String, required: true, unique: true, index: true }, // PK_VisitId
  fkBranchId: { type: String },
  fkRegId: { type: String }, // FK_RegID
  fkPrimaryDoctorId: { type: String },
  visitDate: { type: Date },
  visitTime: { type: String },
  ageYear: { type: Number },
  ageMonth: { type: Number },
  ageDays: { type: Number },
  fkBillCategoryId: { type: String },
  fkPatientLocationId: { type: String },
  isWaiting: { type: Boolean, default: false },
  waitingReason: { type: String },
  fkPrevLocationId: { type: String },

  userHE: { type: String },
  userAR: { type: String },
  userOPT: { type: String },
  userDCT: { type: String },
  userCONS: { type: String },
  userPHY: { type: String },
  userPROC: { type: String },

  fkHEId: { type: String },
  fkARId: { type: String },
  fkOptoId: { type: String },
  fkDoctorId: { type: String },
  fkCouncelorId: { type: String },
  fkProcPersonId: { type: String },
  fkClinicalDeptId: { type: String },
  fkPhysicianId: { type: String },
  isCrossReferred: { type: Boolean, default: false },
  isDilated: { type: Boolean, default: false },
  dilationTime: { type: String },
  fkDilationById: { type: String },
  dilationWith: { type: String },
  returnTime: { type: String },
  fkAppointmentId: { type: String },
  isReview: { type: Boolean, default: false },
  sequence: { type: Number },

  totalWaitingWaitingRoom: { type: Number },
  totalProcessTimeHE: { type: Number },
  totalProcessTimeAR: { type: Number },
  totalProcessTimeOpto: { type: Number },
  totalProcessTimeDr: { type: Number },
  totalProcessTimeCons: { type: Number },
  totalProcessTimeProc: { type: Number },
  totalProcessTimePHY: { type: Number },

  remarks: { type: String },
  fkCreatedById: { type: String },
  isSentSMS: { type: Boolean, default: false },
  pkSynchId: { type: String },
  isOptoExamination: { type: Boolean, default: false },
  isIOPDetail: { type: Boolean, default: false },
  isDrExamination: { type: Boolean, default: false },
  isSurgeryAdvised: { type: Boolean, default: false },
  isWalkIn: { type: Boolean, default: false },

  sendingTimeToAR: { type: String },
  sendingTimeToDr: { type: String },
  sendingTimeToOP: { type: String },
  sendingTimeToCS: { type: String },
  sendingTimeToPR: { type: String },
  sendingTimeToCD: { type: String },
  sendingTimeToPHY: { type: String },

  fkCoOrdinatorId: { type: String },
  fkReferredbyId: { type: String },
  isCalledOpto: { type: Boolean, default: false },
  isCalledDoctor: { type: Boolean, default: false },
  isCalledPharmacy: { type: Boolean, default: false },
  isCalledBilling: { type: Boolean, default: false },
  isCalledDG: { type: Boolean, default: false },
  isCalledCS: { type: Boolean, default: false },
  fkPartyId: { type: String },

  firstInTimeToAR: { type: String },
  firstInTimeToOP: { type: String },
  firstInTimeToDR: { type: String },
  firstInTimeToCons: { type: String },
  firstInTimeToPHY: { type: String },
  firstInTimeToProc: { type: String },
  firstOutTimeToAR: { type: String },
  firstOutTimeToOP: { type: String },
  firstOutTimeToDR: { type: String },
  firstOutTimeToPR: { type: String },
  firstOutTimeToPHY: { type: String },
  firstOutTimeToCons: { type: String },
  firstStartTimeAR: { type: String },
  firstStartTimeOP: { type: String },
  firstStartTimeDR: { type: String },

  oldRegId: { type: String }
}, { timestamps: true });

module.exports = mongoose.model('OpdVisitMaster', OpdVisitMasterSchema);
